### ISSUE TITLE
redis_server.info key missing?

### ISSUE THREAD

**Issue by krejkrejkrej** [allenta/zabbix-template-for-redis#11]
Seems like a very well thought through template for redis. I'm a bit confused though.. the templates reference keys `redis_server.info` and `redis_sentinel.info`, that aren't defined in the zabbix agent configuration file. Is there something I don't understand here?

**Comment by carlosabalde** [comment]
Those are keys of dependent items associated to a master item (e.g. `redis_sentinel.stats["{$REDIS_SENTINEL.LOCATIONS}"]` in the Redis Sentinel template). The master item in the one to be defined in the Zabbix Agent configuration, as shown in the README file.

**Comment by krejkrejkrej** [comment]
Of course! Missed the "dependent item", they aren't used that often. Great template!
