### ISSUE TITLE
Specific instructions needed

### ISSUE THREAD

**Issue by pthreat** [allenta/zabbix-template-for-redis#14]
Hi, thanks for your template, looks good! But I don't really know where should I add the parameters, server? agent ? where? Could you provide better instructions? Thanks

**Comment by davidfb** [comment]
Hi,

The idea is to define User parameters, which are commands executed by Zabbix agent. Therefore, they should be included in the agent's configuration file.

You can read more about UserParameters, here: https://www.zabbix.com/documentation/current/manual/config/items/userparameters
